services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "8080:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=changeme
      - WEBHOOK_URL=http://localhost:8080/
      - GENERIC_TIMEZONE=Asia/Taipei
    volumes:
      - n8n_data:/home/node/.n8n
      - ./shared:/shared
    networks:
      - invoice-network

  python-service:
    image: continuumio/miniconda3:latest
    container_name: invoice-agent-python
    restart: always
    working_dir: /app
    ports:
      - "5001:5000"
    volumes:
      - ./python-scripts:/app
      - ./shared:/shared
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
    networks:
      - invoice-network
    command: >
      bash -c "
        conda create -n invoice-agent python=3.11 -y &&
        echo 'source activate invoice-agent' >> ~/.bashrc &&
        source activate invoice-agent &&
        pip install -r requirements.txt &&
        echo 'Conda environment invoice-agent created successfully!' &&
        echo 'Installed packages:' &&
        pip list &&
        echo 'Running environment validation...' &&
        python env_check.py &&
        echo 'Environment validation passed! Starting main service...' &&
        python enhanced_service.py
      "

volumes:
  n8n_data:

networks:
  invoice-network:
    driver: bridge 